using UnityEditor;
using UnityEngine;

namespace ChonkyMerge.EditorTools
{
    /// <summary>
    /// Proves the shipped levels against the game's own rules.
    ///
    ///   Unity.exe -batchmode -quit -nographics -projectPath . -logFile audit.log
    ///             -executeMethod ChonkyMerge.EditorTools.LevelAudit.Run
    ///
    /// Levels are generated by tools/gen_levels.py, which re-implements the slide
    /// rules in Python. `gen_levels.py verifycs` only proves the file agrees with
    /// *Python*. This runs the real C# SlideSim and BFS over every level instead, so
    /// if the two implementations ever drift apart — a chapter toy handled slightly
    /// differently, an ordering difference — it fails here rather than in a player's
    /// hands, where it would look like a level with an impossible 3-star target.
    ///
    /// Exits 1 on any mismatch so it can gate a build.
    /// </summary>
    public static class LevelAudit
    {
        public static void Run()
        {
            string report = SleepyZoo.PuzzleGame.AuditAllLevels();
            Debug.Log("LEVEL AUDIT\n" + report);
            if (report.Contains("DISAGREE")) EditorApplication.Exit(1);
        }
    }
}
